# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.vm.network 'public_network', ip: '192.168.0.123', bridge: 'br0'

  #config.vm.provision "shell", run: "always", inline:"sudo route add default gw 192.168.0.1" 
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../playbook/vagrant.yml"
    ansible.extra_vars = {
       "ipaddr"=> "192.168.0.123",
       "gw"=> "192.168.0.1",
       "device"=> "eth1"
    }
  end
end
