---
- name: Install base command
  become: true
  become_user: root
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "net-tools"
    - "wget"
    - "zip"
    - "unzip"
    - "git"

- name : install eth1
  become: true
  become_user: root
  template: 
    src: "roles/init/templates/ifcfg-eth1.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-eth1"
 
